lesson: SpringBoot


enterprise:
  name: itcast
  age: 14
  subject:
    - java
    - 前端
    - 大数据

spring:
  profiles:
    active: pro
---
server:
  port: 80
spring:
  profiles: dev

---
server:
  port: 81
spring:
  profiles: pro

---

server:
  port: 82
spring:
  profiles: test
---